url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Rui Hua" # the name of your site, e.g. ACME Corp.
description: "Postdoctoral Research Fellow | Shirley Ryan Abilitylab & Northwestern University"
